### ISSUE TITLE
Todos

### ISSUE THREAD

**Issue by ines** [ines/course-starter-r#1]
I don't have much experience with R, so I hope that you lovely R people can help me out here 😃 

To my surprise, the basics all worked pretty smoothly! There's an R binder that executes code and plots work pretty much out-of-the-box (although they have to be wrapped in `print` statements due to [this issue](https://github.com/IRkernel/IRkernel/issues/597) to prevent a warning from showing up). You can see it in action here: https://course-starter-r.netlify.com

Here's what's still outstanding:

- [ ] A better example. I [copy-pasted something together](https://github.com/ines/course-starter-r/tree/master/exercises) for the current exercises. The example should ideally show a few different things that are possible in the current framework.
- [ ] Testing, especially the plotting stuff.
- [ ] Improve validation when the user clicks "submit".

This part is handled by the `testTemplate`. For Python, it'd look something like this:

```
__solution__ = """${solution}"""
${solution}

${test}
try:
    test()
except AssertionError as e:
    print(e)
```

Under the hood, the app replaces `${solution}` with the **string value** of the submitted user code and `${test}` with the contents of the [respective test file](https://github.com/ines/course-starter-r/blob/master/exercises/test_01_03.R). So in the above example, we execute the solution, but also make it available as a string. This allows checking the *actual* objects that were created, but also doing string matches (like, `print(doc.text) in __solution__`).

For R, I currently have this (which works okay so far):

```r
${solution}

${test}

tryCatch({
    test()
}, error = function(e) {
    cat(paste(e[1]))
})
```

The `tryCatch` is supposed to hide the traceback – otherwise, the user would see what caused the error / `stop` – which is usually a test that reveals the solution.

I haven't vet added the string value, because **I'm not sure how to represent multi-line strings like Python's `"""string""` in R**. We have to expect that `${solution}` includes various quotation marks, so if we paste it in, we don't want to mess up the string. Alternatively, maybe there's an easy way to escape / unescape quotes etc?

**Comment by AndreaPi** [comment]
You can split a string over as many lines as you want, R won't mind:

``` r
a_long_string <- "Hi! I'm a pretty long string. 
You can split me over as many
lines as you want, I won't mind at all. "
a_long_string
#> [1] "Hi! I'm a pretty long string. \nYou can split me over as many\nlines as you want, I won't mind at all. "
```

<sup>Created on 2019-04-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

However, as you can see, it will introduce some line breaks. If you want to get rid of them, do

```
a_better_looking_long_string <- gsub("\\n"," ",a_long_string)
a_better_looking_long_string
#> [1] "Hi! I'm a pretty long string.  You can split me over as many lines as you want, I won't mind at all. "
```

Escaping quotes can look a bit weird:

``` r
a_string_with_quotes <- "Hi! I'm a string with \"air-\"quotes"
a_string_with_quotes
#> [1] "Hi! I'm a string with \"air-\"quotes"
```
It looks like you didn't really escape the quotes, but it's just that R's default `print` method will show the escape characters used in a string. If you display the content of `a_string_with_quotes` using a function which does much less conversion than `print`, such as `cat`, you'll see that the content is actually what you want:

```
cat(a_string_with_quotes)
#> Hi! I'm a string with "air-"quotes

```

Does this help?

**Comment by ines** [comment]
@AndreaPi Thanks for writing this up, this is all really useful info 👍 

But how would you solve the following problem:

```javascript
// In JavaScript
const code = `I'm a string with "air-"quotes`

const rCode = `
# This is the inside of an R file
r_string <- "${code}"
`
```

This is pretty much how the app is putting the tests and code together under the hood – it's generating an R file as a string. At the moment, the above would break, because it'd create output like this:

```r
r_string <- "I'm a string with "air-"quotes"
```

One option would be to wrap the string in `"` and replace all `"` in the string with `\"`, like this:

```javascript
const code = `I'm a string with "air-"quotes`.replace(/"/g, '\\"')
```

That'd result in the following, which should be valid?

```r
r_string <- "I'm a string with \"air-\"quotes"
```

But there might be unintended side-effects of this that I'm not considering at the moment? And of course there might also be a more elegant way to do this.

**Comment by MikeJohnPage** [comment]
If not pre-processing the string before reading it into R, perhaps using `readline()` could work to preserve quotation marks?  See this [link](https://stackoverflow.com/questions/31857819/read-a-string-with-single-and-doubles-quotes?answertab=votes#tab-top).

**Comment by AndreaPi** [comment]
@ines `r_string` is definitely valid (just tested in R). I don't think there should be any side effects.
