### ISSUE TITLE
blank page in localhost when click on exercise

### ISSUE THREAD

**Issue by awconway** [ines/course-starter-r#3]
Hi - i really love this package thanks for developing it. I'm having a problem with gatsby develop so this may or may not be something you can help with. When i run gatsby develop everything compiles successfully and the index page as well as chapter pages show up fine but now when i click on an exercise it just shows a blank page. 

However, when I deploy to netlify everything works fine. Similarly gatsby build works fine and shows all exercises on localhost:9000. The only warning after gatsby build I got was:

success Building production JavaScript and CSS bundles — 45.995 s
success Building static HTML for pages — 4.357 s — 15/15 25.65 pages/second
warn app-bc1df976b41477c5ba00.js is 2.22 MB, and won't be precached. Configure
Generated public/sw.js, which will precache 7 files, totaling 257024 bytes.

Do you have any tips for how I can try and find out what is going wrong with gatsby develop? It's getting a bit annoying to have to commit-push to see changes.

Thanks very much.

**Comment by ines** [comment]
It's possible that this is a caching issue. Gatsby caches the built app and on top of it, it also uses a service worker. It can sometimes happen that your build is out of sync and it's trying to load things that aren't there. When the blank page appears, check out the console in your browser's developer tools – does it show an error there?

Also, try the following to reset the cache and start from scratch: 

* run `npm run clear` (which is a [shortcut](https://github.com/ines/course-starter-r/blob/master/package.json#L46) for `rm -rf .cache`)
* empty the `/public` folder (which contains the latest build)
* delete your browser's cookies and local storage for `localhost:9000`, and unregister the service worker (in Chrome, that should be in the "Application" tab in the developer tools)

**Comment by awconway** [comment]
Thanks - I tried your suggestions for clearing cache and public folder but still get the same blank pages. There are errors that show up in the browser dev tools with localhost:8000. Any ideas for for how I should go about fixing?


![Screen Shot 2019-06-26 at 10 07 53 AM](https://user-images.githubusercontent.com/34257353/60189528-081bb900-97ff-11e9-8d2e-4911241e7003.png)
![Screen Shot 2019-06-26 at 10 11 03 AM](https://user-images.githubusercontent.com/34257353/60189529-081bb900-97ff-11e9-8b71-c3a244f7fb6f.png)

**Comment by ines** [comment]
Hmmm, this looks a lot like ines/course-starter-python#14 🤔

The traceback also looks very similar to nfl/react-helmet#373 and nfl/react-helmet#437... which eventually led me to this: https://www.gatsbyjs.org/packages/gatsby-plugin-react-helmet/#compatibility-with-react-168-useeffect-hook

Do any of the suggestions there work for you?

**Comment by awconway** [comment]
Thanks so much! Updating gatsby-plugin-react-helmet to latest version and react-helmet to v6.0.0beta did the trick
