### ISSUE TITLE
Adding a little more documentation

### ISSUE THREAD

**Issue by laderast** [ines/course-starter-r#4]
Hi @ines - I wrote up this documentation on how the course repo works for one of our collaborators: https://github.com/laderast/RBootcamp/issues/1

I'd be happy to integrate it into the readme.md if you think it's useful.

**Comment by ines** [comment]
Oh wow, this is really cool and looks like a lot of work – thanks! And yes, if you'd like to submit a PR to the README, that'd be great. It'd also be good to mention `decampr` here 👍

**Comment by laderast** [comment]
Great! I'll submit a pull request.
